using System;
using System.Collections.Generic;
using System.Text;

namespace Ffd.Data
{
    public class Lead : Customer
    {
        ///// <summary>
        ///// Enumerations for the lead sources.
        ///// </summary>
        ///// <remarks>
        ///// Auto-generated by the TypeGen program.
        ///// </remarks>
        //public enum LeadSourceCodeType
        //{
        //    lscFundraisingIdeasWebsite = 1
        //}

        /// <summary>
        /// How the lead prefers to be contacted.
        /// </summary>
        public enum BestContactMethodType
        {
            NotSpecified = 0,
            Email = 1,
            RegularMail = 2,
            Phone = 3
        }

        /// <summary>
        /// Lead status codes.
        /// </summary>
        /// <remarks>
        /// Auto-generated by the TypeGen program.
        /// </remarks>
        public enum LeadStatusCode
        {
            lscNotSet = 0,

            lscInserted = 1,
            lscEvaluatedNotCandidateNotEmailed = 2,
            lscEvaluatedGoodCandidateEmailed = 3,
            lscEmailSent = 4,
            lscEmailBounced1 = 5,
            lscInvalidEmailAddress = 6,
            lscUnsubscribeRequestReceived = 7,
            lscLeadOutputToMailingListCSV = 8,
            lscLeadMailedPostcard = 9,
	        lscLeadMailed2NdPostcard = 10,
	        lscLeadMailed3RdPostcard = 11,
	        lscLeadMailed4ThPostcard = 12,
	        lscLeadMailed5ThPostcard = 13,
	        lscInvalidMailingAddress = 14
        }

        /// <summary>
        /// Lead source code.
        /// </summary>
        public enum LeadSourceCodeTypes
        {
            lscNotSet = 0,

	        lscFundraisingIdeasWebsite = 1,
	        lscHighSchoolsComWebsite = 2
        }

        private int _leadSourceCode = -1;
        private string _leadInfoText = string.Empty;
        private DateTime _leadDate = DateTime.MinValue;
        private BestContactMethodType _bestContactMethod = BestContactMethodType.NotSpecified;
        private LeadStatusCode _leadStatusCode = LeadStatusCode.lscNotSet;
        private bool _isSchool;
        private bool _isAthlethics;
        //private string _templateDescShort = string.Empty;
        private Template _templateCurrent = null;
        private int _schoolTotalEnrollment = -1;


	    public int LeadSourceCode
	    {
		    get { return _leadSourceCode;}
		    set { _leadSourceCode = value;}
	    }

        public string LeadInfoText
        {
            get { return _leadInfoText; }
            set { _leadInfoText = value; }
        }

        public BestContactMethodType BestContactMethod
        {
            get { return _bestContactMethod; }
            set { _bestContactMethod = value; }
        }

        public LeadStatusCode LeadStatusCodeCurrent
        {
            get { return _leadStatusCode; }
            set { _leadStatusCode = value; }
        }

        public BestContactMethodType ParseContactMethodDescription(string description)
        {
            _bestContactMethod = BestContactMethodType.NotSpecified;

            if (description == "E-mail")
            {
                _bestContactMethod = BestContactMethodType.Email;
            }
            else if (description == "Surface Mail")
            {
                _bestContactMethod = BestContactMethodType.RegularMail;
            }
            else if (description == "Telephone")
            {
                _bestContactMethod = BestContactMethodType.Phone;
            }

            return _bestContactMethod;
        }

        public bool IsSchool
        {
            get { return _isSchool; }
            set { _isSchool = value; }
        }

        public bool IsAthletics
        {
            get { return _isAthlethics; }
            set { _isAthlethics = value; }
        }

        public int SchoolTotalEnrollment
        {
            get { return _schoolTotalEnrollment; }
            set { _schoolTotalEnrollment = value; }
        }

        ///// <summary>
        ///// If this applies to a template, the appropriate template description.
        ///// </summary>
        //public string TemplateDescShort
        //{
        //    get { return _templateDescShort; }
        //    set { _templateDescShort = value; }
        //}

        /// <summary>
        /// The current template for the lead, or null if none.
        /// </summary>
        public Template TemplateCurrent
        {
            get { return _templateCurrent; }
            set { _templateCurrent = value; }
        }


    }
}
